### ISSUE TITLE
Fails to get emoji guild

### ISSUE THREAD

**Issue by ammongit** [strinking/statbot#8]
I get the following error when trying to do `upsert_emoji()`:

```py
Traceback (most recent call last):
  File "/home/ammon/.local/lib/python3.6/site-packages/discord/client.py", line 197, in _run_event
    yield from coro(*args, **kwargs)
  File "/home/ammon/Git/statbot/statbot/client.py", line 174, in on_reaction_add
    async def on_reaction_clear(self, message, reactions):
  File "/home/ammon/Git/statbot/statbot/sql.py", line 344, in add_reaction
    'channel_id': message.channel.id,
  File "/home/ammon/Git/statbot/statbot/sql.py", line 577, in upsert_emoji
  File "/home/ammon/Git/statbot/statbot/sql.py", line 218, in _emoji_values
    self.db.execute(ups)
AttributeError: 'PartialReactionEmoji' object has no attribute 'guild'
```

**Comment by ammongit** [comment]
Since we're focusing on MVP, for now I'm going to table this issue, and put emojis in the same category as pins. (i.e. wontfix until 1.0)
